### PR TITLE
#160618104 Create Articles CRUD

### PR DESCRIPTION
**Pull request by MaejorAli**
## What does this PR do?
- This PR shows how articles controller is created which performs the CRUD functions
## Description of Task to be completed?
- Create articles controller which performs CRUD functions
- enables user to create articles
- enables user to fetch all articles
- enables user to fetch only one article
- enables user to modify articles
- enables user to delete articles
## How should this be manually tested?
- npm run test
## Any background context you want to provide?
- None
## What are the relevant pivotal tracker stories?
[#160618104](https://www.pivotaltracker.com/story/show/160618104)
## Screenshots (if appropriate)
- None
## Questions:
- None

### CODE REVIEW

**Review by tonyguesswho — APPROVED** [review]
Looks good to me, Nice job

**Review by Phunmbi — APPROVED** [review]
LGTM. Nice touch with the JS Doc comments.

**Review by AdinoyiSadiq — APPROVED** [review]
Looks good.

**Comment by damafeez** [comment]
LGTM (Looks Good To Me)

**Review by VictorUkafor — APPROVED** [review]
Great job. This looks good. Thanks for reverting all es5 require statement to import in es6

**Pull request merged**
